### ISSUE TITLE
首页没有[更多文章]按钮

### ISSUE THREAD

**Issue by liunaijie** [mizoreyo/hexo-theme-insnow#1]
Hi 这个主题非常简洁, 看着不错
但是在主页限制了要显示的文章数量, 并且没有显示全部或者分页显示的功能, 并且没有搜索功能, 所以当文章变多之后, 就无法找到相关的文章.
希望作者帮忙更新下这个功能, 感谢

**Comment by xmizore** [comment]
刚刚增加了分页组件，你更新看看

**Comment by liunaijie** [comment]
Cool, Thanks for help
